$('.owl-carousel').owlCarousel({
    center: true,
    loop:true,
    nav:true,
    autoplay:true,
    autoplayTimeout:2500,
    responsive:{
        0:{
            items:1
        },
        375:{
            items:1.08
        },
        400:{
            items:1.2
        },
        600:{
            items:2.2
        },
        1000:{
            items:2.5
        },
        1300:{
            items:3
        },
        1400:{
            items:4
        },
        1900:{
            items:5
        },
        2560:{
            items:6
        }
    }
})